apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
  sessionAffinity: ClientIP
