apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-consumer
  labels:
    app: profile-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-consumer
  template:
    metadata:
      labels:
        app: profile-consumer
    spec:
      containers:
        - name: profile-consumer
          image: gcr.io/unified-freedom-443118-s0/profile-consumer:latest
          env:
            - name: RABBIT_MQ
              value: "amqp://darshan:darshan@35.185.24.216:5672/"
