apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    app: redis
spec:
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
      nodePort: 30079  # Choose any port within the range 30000-32767
  selector:
    app: redis
  type: NodePort
